spring:
  application:
    name: micropagamentos
#  cache:
#    type: none
  datasource:
    hikari:
      pool-name: poll_microinscricoes
      maxLifetime: 1800000
      connection-timeout: 40000
      idle-timeout: 300000
      maximum-pool-size: 2
    url: jdbc:mariadb://${DB_HOST:micropagamentos16postgres:5432}/${DB_DATABASE:micropagamentos}?serverTimezone=UTC
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8
    characterEncoding: UTF-8
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        type:
          enumType:
            type: pgsql_enum
        jdbc:
          log:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

