server:
  port: 0

spring:

  application:
    name: micropagamentos

  datasource:
    url: jdbc:postgresql://${DB_HOST:micropagamentos16postgres}:${DB_PORT:5432}/${DB_NAME:micropagamentos}?serverTimezone=UTC
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8
    characterEncoding: UTF-8
    hikari:
      pool-name: poll_micropagamentos
      maxLifetime: 1800000
      connection-timeout: 40000
      idle-timeout: 300000
      maximum-pool-size: 2

  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        type:
          enumType:
            type: pgsql_enum
        jdbc:
          log:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:kafka:9092}
    topic:
      pagamento-success: pagamento-success
      orchestrator: orchestrator
      pagamento-fail: pagamento-fail
    consumer:
      group-id: ${spring.application.name}:-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 30

