version: "3.9"

services:

  microusuarios8mysql:
    container_name: microusuarios8mysql
    image: mysql:8.0.17
    restart: always
    networks:
      - babystepsnet
    environment:
      - MYSQL_DATABASE=microusuarios
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3307:3306"
    volumes:
      - data-mysql:/var/lib/mysql

  microinscricoes6mongo:
    container_name: microinscricoes6mongo
    image: mongo:latest
    restart: always
    networks:
      - babystepsnet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "27018:27017"
    volumes:
      - data-mongodb:/data/db

  microtorneios16postgres:
    container_name: microtorneios16postgres
    image: postgres:16.0
    restart: always
    networks:
      - babystepsnet
    environment:
      - POSTGRES_DB=microtorneios
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - data-postgresql:/var/lib/postgresql/data

  micropagamentos16postgres:
    container_name: micropagamentos16postgres
    image: postgres:16.0
    restart: always
    networks:
      - babystepsnet
    environment:
      - POSTGRES_DB=micropagamentos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - data-postgresq:/var/lib/postgresql/data

  microtimes10mariadb:
    container_name: microtimes10mariadb
    image: mariadb:10.6.16-focal
    restart: always
    networks:
      - babystepsnet
    environment:
      - MARIADB_DATABASE=microtimes
      - MARIADB_ROOT_PASSWORD=mariadb
    ports:
      - "3305:3306"
    volumes:
      - data-mariadb:/var/lib/mysql

  micronoticias16postgres:
    container_name: micronoticias16postgres
    image: postgres:16.0
    restart: always
    networks:
      - babystepsnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: micronoticias
    ports:
      - "5535:5432"
    volumes:
      - data-postgres:/var/lib/postgresql/data


  kafka:
    container_name: kafka
    #    image: confluentinc/cp-kafka:7.5.3
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - babystepsnet
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data

  redpanda-console:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - babystepsnet
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"


  eurekaserver:
    container_name: eurekaserver
    restart: always
    networks:
      - babystepsnet
    build:
      context: ./
      dockerfile: ./eurekaserver/Dockerfile
    ports:
      - "8761:8761"

  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
    restart: always
    networks:
      - babystepsnet
    ports:
      - "8000:8000"
    depends_on:
      - eurekaserver


  microusuarios:
    container_name: microusuarios
    build:
      context: ./
      dockerfile: ./microusuarios/Dockerfile
    restart: always
    networks:
      - babystepsnet
    env_file:
      - ./microusuarios/.env
    depends_on:
      - eurekaserver
      - microusuarios8mysql

  microinscricoes:
    container_name: microinscricoes
    build:
      context: ./
      dockerfile: ./microinscricoes/Dockerfile
    restart: always
    networks:
      - babystepsnet
#    env_file:
#      - ./microinscricoes/.env
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_DB_URI=mongodb://admin:123456@microinscricoes6mongo:27017
    depends_on:
      - eurekaserver
      - microinscricoes6mongo
      - kafka

  microtorneios:
    container_name: microtorneios
    build:
      context: ./
      dockerfile: ./microtorneios/Dockerfile
    restart: always
    networks:
      - babystepsnet
    env_file:
      - ./microtorneios/.env
    depends_on:
      - eurekaserver
      - microtorneios16postgres
      - kafka

  micropagamentos:
    container_name: micropagamentos
    build:
      context: ./
      dockerfile: ./micropagamentos/Dockerfile
    restart: always
    networks:
      - babystepsnet
    env_file:
      - ./micropagamentos/.env
    depends_on:
      - eurekaserver
      - micropagamentos16postgres
      - kafka

  microtimes:
    container_name: microtimes
    build:
      context: ./
      dockerfile: ./microtimes/Dockerfile
    restart: always
    networks:
      - babystepsnet
    env_file:
      - ./microtimes/.env
    depends_on:
      - eurekaserver
      - microtimes10mariadb
      - kafka

  orchestrator:
    container_name: orchestrator
    build:
      context: ./
      dockerfile: ./orchestrator/Dockerfile
    restart: always
    networks:
      - babystepsnet
    environment:
      - KAFKA_BROKER=kafka:29092
    depends_on:
      - eurekaserver
      - microinscricoes
      - microtimes
      - micropagamentos
      - microtorneios
      - kafka

  micronoticias:
    container_name: micronoticias
    build:
      context: ./
      dockerfile: ./micronoticias/Dockerfile
    restart: always
    networks:
      - babystepsnet
    env_file:
      - ./micronoticias/.env
    depends_on:
      - eurekaserver
      - micronoticias16postgres


  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk21
    privileged: true
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - data-docker:/usr/local/bin/docker
    networks:
      - babystepsnet


volumes:
  data-mysql:
    name: data-mysql
  data-mongodb:
    name: data-mongodb
  data-postgresql:
    name: data-postgresql
  data-postgresq:
    name: data-postgresq
  data-mariadb:
    name: data-mariadb
  data-postgres:
    name: data-postgres
  data-docker:
    name: data-docker

networks:
  babystepsnet:
    name: babystepsnet
    driver: bridge

