version: "3.9"

services:
  mysql8microusuarios:
    container_name: mysql8microusuarios
    image: mysql:8.0.17
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: microusuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - babystepsnet

  postgres16micronoticias:
    container_name: postgres16micronoticias
    image: postgres:16.0
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: micronoticias
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - babystepsnet

  microusuarios:
    container_name: microusuarios
    build:
      context: ./
      dockerfile: ./microusuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./microusuarios/.env
    networks:
      - babystepsnet
    depends_on:
      - mysql8microusuarios
    restart: always

  micronoticias:
    container_name: micronoticias
    build:
      context: ./
      dockerfile: ./micronoticias/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./micronoticias/.env
    networks:
      - babystepsnet
    depends_on:
      - postgres16micronoticias
      - microusuarios
    restart: always

  jenkins:
    container_name: jenkins
    user: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"
    volumes:
      - ./jenkins:/var/jenkins
#      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djava.util.logging.config.file=/var/jenkins/log.properties -Djenkins.install.runSetupWizard=false
      - JAVA_HOME=/usr/local/openjdk-21
    networks:
      - jenkinsnet

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
  jenkins_home:
    name: jenkins

networks:
  babystepsnet:
    name: babystepsnet
  jenkinsnet:
    name: jenkinsnet
    driver: bridge
