version: "3.9"

services:
  eurekaserver:
    container_name: eurekaserver
    build:
      context: ./
      dockerfile: ./eurekaserver/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - babystepsnet
    restart: always

  mysql8microusuarios:
    container_name: mysql8microusuarios
    image: mysql:8.0.17
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: microusuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - babystepsnet

  postgres16micronoticias:
    container_name: postgres16micronoticias
    image: postgres:16.0
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: micronoticias
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - babystepsnet

  microusuarios:
    container_name: microusuarios
    build:
      context: ./
      dockerfile: ./microusuarios/Dockerfile
#    ports:
#      - "8001:8001"
    env_file:
      - ./microusuarios/.env
    networks:
      - babystepsnet
    depends_on:
      - mysql8microusuarios
    restart: always

  micronoticias:
    container_name: micronoticias
    build:
      context: ./
      dockerfile: ./micronoticias/Dockerfile
#    ports:
#      - "8002:8002"
    env_file:
      - ./micronoticias/.env
    networks:
      - babystepsnet
    depends_on:
      - postgres16micronoticias
      - microusuarios
    restart: always

  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - babystepsnet
    depends_on:
      - eurekaserver
      - microusuarios
      - micronoticias
    restart: always

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk21
    privileged: true
    user: root
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - data-docker:/usr/local/bin/docker
    networks:
      - babystepsnet

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
  data-docker:
    name: data-docker
#  jenkins_home:
#    name: jenkins_home
#    driver: local
#  jenkins-docker-certs:
#    name: jenkins-docker-certs

networks:
  babystepsnet:
    name: babystepsnet

