spring:
  application:
    name: eurekaserver
  cache:
    type: none

server:
  port: 8761

eureka:
  server:
    responseCacheUpdateIntervalMs: 30000
    evictionIntervalTimerInMs: 60000
  client:
    register-with-eureka: false
    fetch-registry: false


ribbon:
  eureka:
    enabled: true

logging:
  file:
    path: /app/logs

