pipeline {
    agent any

    tools {
        maven 'mvn'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Check..'
                checkout scm
            }
        }

        stage('Pull Configurations') {
            steps {
                echo 'Config..'

             }
        }

        stage('Build') {
            steps {
                echo 'Fase de construção'
                git branch: 'master', url: 'https://github.com/juniorsmartins/site.git'
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS'
              }
            }
            steps {
                echo 'Deploying....'
            }
        }
    }
}

