server:
  port: 0

spring:

  application:
    name: orchestrator

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:kafka:9092}
    topic:
      start-saga: start-saga
      orchestrator: orchestrator
      finish-success: finish-success
      finish-fail: finish-fail
    consumer:
      group-id: ${spring.application.name}:-group
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}


